Update docker-compose.openlmis-dev.yml
The new added image is a fork from docker.io/hauptmedia/proftpd:latest, which is the image we are currently using. It has been giving us the error below when running the stack.

ERROR: Docker Image Format v1 and Docker Image manifest version 2, schema 1 support has been removed. Suggest the author of docker.io/hauptmedia/proftpd:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/

This image is replaced with driesva/proftpd:latest